// AUTO-GENERATED by mcp-query codegen. Do not edit.

export interface GeneratedToolMap {
  /** Echoes back the input string */
  "echo": {
    args: {
      /** Message to echo */
      message: string;
    };
    result: unknown;
  };
  /** Demonstrates how annotations can be used to provide metadata about content. */
  "get-annotated-message": {
    args: {
      /** Type of message to demonstrate different annotation patterns */
      messageType: "error" | "success" | "debug";
      /** Whether to include an example image */
      includeImage?: boolean;
    };
    result: unknown;
  };
  /** Returns all environment variables, helpful for debugging MCP server configuration */
  "get-env": {
    args: Record<string, unknown>;
    result: unknown;
  };
  /** Returns up to ten resource links that reference different types of resources */
  "get-resource-links": {
    args: {
      /** Number of resource links to return (1-10) */
      count?: number;
    };
    result: unknown;
  };
  /** Returns a resource reference that can be used by MCP clients */
  "get-resource-reference": {
    args: {
      resourceType?: "Text" | "Blob";
      /** ID of the text resource to fetch */
      resourceId?: number;
    };
    result: unknown;
  };
  /** Returns structured content along with an output schema for client data validation */
  "get-structured-content": {
    args: {
      /** Choose city */
      location: "New York" | "Chicago" | "Los Angeles";
    };
    result: unknown;
  };
  /** Returns the sum of two numbers */
  "get-sum": {
    args: {
      /** First number */
      a: number;
      /** Second number */
      b: number;
    };
    result: unknown;
  };
  /** Returns a tiny MCP logo image. */
  "get-tiny-image": {
    args: Record<string, unknown>;
    result: unknown;
  };
  /** Compresses a single file using gzip compression. Depending upon the selected output type, returns either the compressed data as a gzipped resource or a resource link, allowing it to be downloaded in a subsequent request during the current session. */
  "gzip-file-as-resource": {
    args: {
      /** Name of the output file */
      name?: string;
      /** URL or data URI of the file content to compress */
      data?: string;
      /** How the resulting gzipped file should be returned. 'resourceLink' returns a link to a resource that can be read later, 'resource' returns a full resource object. */
      outputType?: "resourceLink" | "resource";
    };
    result: unknown;
  };
  /** Simulates a deep research operation that gathers, analyzes, and synthesizes information. Demonstrates MCP task-based operations with progress through multiple stages. If 'ambiguous' is true and client supports elicitation, sends an elicitation request for clarification. */
  "simulate-research-query": {
    args: {
      /** The research topic to investigate */
      topic: string;
      /** Simulate an ambiguous query that requires clarification (triggers input_required status) */
      ambiguous?: boolean;
    };
    result: unknown;
  };
  /** Toggles simulated, random-leveled logging on or off. */
  "toggle-simulated-logging": {
    args: Record<string, unknown>;
    result: unknown;
  };
  /** Toggles simulated resource subscription updates on or off. */
  "toggle-subscriber-updates": {
    args: Record<string, unknown>;
    result: unknown;
  };
  /** Demonstrates a long running operation with progress updates. */
  "trigger-long-running-operation": {
    args: {
      /** Duration of the operation in seconds */
      duration?: number;
      /** Number of steps in the operation */
      steps?: number;
    };
    result: unknown;
  };
}

export type ToolName = "echo" | "get-annotated-message" | "get-env" | "get-resource-links" | "get-resource-reference" | "get-structured-content" | "get-sum" | "get-tiny-image" | "gzip-file-as-resource" | "simulate-research-query" | "toggle-simulated-logging" | "toggle-subscriber-updates" | "trigger-long-running-operation";

export type ToolArgs<N extends ToolName> = GeneratedToolMap[N]["args"];
export type ToolResult<N extends ToolName> = GeneratedToolMap[N]["result"];

export interface GeneratedPromptMap {
  "args-prompt": {
    city: string;
    state?: string;
  };
  "completable-prompt": {
    department: string;
    name: string;
  };
  "resource-prompt": {
    resourceType: string;
    resourceId: string;
  };
  "simple-prompt": {
    [k: string]: string;
  };
}

export type PromptName = "args-prompt" | "completable-prompt" | "resource-prompt" | "simple-prompt";

export type ResourceTemplateUri = "demo://resource/dynamic/text/{resourceId}" | "demo://resource/dynamic/blob/{resourceId}";
