// Codegen — turn a server's `tools/list` (each tool carries a JSON Schema input)
// into typed TypeScript. This is the MCP analog of OpenAPI/Connect codegen: since
// MCP servers are polyglot and decoupled, types come from the schema, not TS
// inference. Output is a `GeneratedToolMap` + a `ToolName` union that downstream
// typed hooks can key off.

export interface JSONSchema {
  type?: string | string[];
  properties?: Record<string, JSONSchema>;
  required?: string[];
  items?: JSONSchema;
  enum?: unknown[];
  anyOf?: JSONSchema[];
  oneOf?: JSONSchema[];
  additionalProperties?: boolean | JSONSchema;
  description?: string;
}

export interface ToolLike {
  name: string;
  description?: string;
  inputSchema?: JSONSchema;
}

/** Convert a single JSON Schema node to a TS type expression. */
export function jsonSchemaToTS(schema: JSONSchema | undefined, indent = 0): string {
  if (!schema) return "unknown";
  if (schema.enum) return schema.enum.map((v) => JSON.stringify(v)).join(" | ") || "never";
  if (schema.anyOf) return schema.anyOf.map((s) => jsonSchemaToTS(s, indent)).join(" | ");
  if (schema.oneOf) return schema.oneOf.map((s) => jsonSchemaToTS(s, indent)).join(" | ");

  const type = Array.isArray(schema.type) ? schema.type[0] : schema.type;
  switch (type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      return `Array<${jsonSchemaToTS(schema.items, indent)}>`;
    case "object":
    case undefined:
      return objectToTS(schema, indent);
    default:
      return "unknown";
  }
}

function objectToTS(schema: JSONSchema, indent: number): string {
  const props = schema.properties;
  if (!props || Object.keys(props).length === 0) {
    return schema.additionalProperties === false ? "Record<string, never>" : "Record<string, unknown>";
  }
  const pad = "  ".repeat(indent + 1);
  const closePad = "  ".repeat(indent);
  const required = new Set(schema.required ?? []);
  const lines = Object.entries(props).map(([key, sub]) => {
    const optional = required.has(key) ? "" : "?";
    const doc = sub.description ? `${pad}/** ${sub.description.replace(/\*\//g, "*\\/")} */\n` : "";
    return `${doc}${pad}${tsKey(key)}${optional}: ${jsonSchemaToTS(sub, indent + 1)};`;
  });
  return `{\n${lines.join("\n")}\n${closePad}}`;
}

function tsKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

/** Emit a full module: GeneratedToolMap + ToolName union + per-tool arg aliases. */
export function generateToolTypes(tools: ToolLike[], opts: { banner?: boolean } = {}): string {
  const banner = opts.banner === false ? "" : "// AUTO-GENERATED by mcp-query codegen. Do not edit.\n\n";
  const sorted = [...tools].sort((a, b) => a.name.localeCompare(b.name));

  const entries = sorted
    .map((t) => {
      const doc = t.description ? `  /** ${t.description.replace(/\*\//g, "*\\/")} */\n` : "";
      return `${doc}  ${JSON.stringify(t.name)}: {\n    args: ${jsonSchemaToTS(t.inputSchema, 2)};\n    result: unknown;\n  };`;
    })
    .join("\n");

  const union = sorted.length ? sorted.map((t) => JSON.stringify(t.name)).join(" | ") : "never";

  return (
    banner +
    `export interface GeneratedToolMap {\n${entries}\n}\n\n` +
    `export type ToolName = ${union};\n\n` +
    `export type ToolArgs<N extends ToolName> = GeneratedToolMap[N]["args"];\n` +
    `export type ToolResult<N extends ToolName> = GeneratedToolMap[N]["result"];\n`
  );
}
